//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlCaPhe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class baiViet
    {
        public int maBaiViet { get; set; }
        public string loaiTin { get; set; }
        public string tenBaiViet { get; set; }
        public string noiDungTomTat { get; set; }
        public string noiDungBaiViet { get; set; }
        public Nullable<System.DateTime> ngayTao { get; set; }
        public Nullable<int> trangThai { get; set; }
        public Nullable<System.DateTime> ngayDang { get; set; }
        public byte[] hinhDD { get; set; }
        public string nguoiTao { get; set; }
        public Nullable<bool> hienTrangChu { get; set; }
        public string ghiChu { get; set; }
    
        public virtual taiKhoan taiKhoan { get; set; }
    }
}
