//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlCaPhe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BanChoNgoi
    {
        public BanChoNgoi()
        {
            this.ctDatBans = new HashSet<ctDatBan>();
            this.hoaDonOrders = new HashSet<hoaDonOrder>();
        }
    
        public int maBan { get; set; }
        public string tenBan { get; set; }
        public int maKhuVuc { get; set; }
        public int sucChua { get; set; }
        public byte[] hinhAnh { get; set; }
        public string gioiThieu { get; set; }
        public Nullable<int> trangThai { get; set; }
        public string ghiChu { get; set; }
    
        public virtual khuVuc khuVuc { get; set; }
        public virtual ICollection<ctDatBan> ctDatBans { get; set; }
        public virtual ICollection<hoaDonOrder> hoaDonOrders { get; set; }
        public virtual hoaDonTam hoaDonTam { get; set; }
    }

    public class svBanChoNgoi
    {
        public int maBan { get; set; }
        public string tenBan { get; set; }
        public int maKhuVuc { get; set; }
        public int sucChua { get; set; }
        public byte[] hinhAnh { get; set; }
        public string gioiThieu { get; set; }
        public int trangThai { get; set; }
        public string ghiChu { get; set; }
    }
}
