//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlCaPhe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangGiaoViec
    {
        public BangGiaoViec()
        {
            this.ctBangGiaoViecs = new HashSet<ctBangGiaoViec>();
        }
    
        public int maBang { get; set; }
        public string tenDangNhap { get; set; }
        public System.DateTime ngayLap { get; set; }
        public bool trangThai { get; set; }
        public string ghiChu { get; set; }
    
        public virtual taiKhoan taiKhoan { get; set; }
        public virtual ICollection<ctBangGiaoViec> ctBangGiaoViecs { get; set; }
    }
}
