//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlCaPhe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class caLamViec
    {
        public caLamViec()
        {
            this.ctBangGiaoViecs = new HashSet<ctBangGiaoViec>();
        }
    
        public int maCa { get; set; }
        public string tenCa { get; set; }
        public int buoi { get; set; }
        public System.TimeSpan batDau { get; set; }
        public System.TimeSpan ketThuc { get; set; }
        public string ghiChu { get; set; }
    
        public virtual ICollection<ctBangGiaoViec> ctBangGiaoViecs { get; set; }
    }
}
