//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlCaPhe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cauHinh
    {
        public string tenQuan { get; set; }
        public string gioiThieu { get; set; }
        public string diaChi { get; set; }
        public string hotLine { get; set; }
        public string email { get; set; }
        public string facebook { get; set; }
        public string googlePlus { get; set; }
        public string twitter { get; set; }
        public string kinhDo { get; set; }
        public string viDo { get; set; }
        public byte[] loGo { get; set; }
        public string ghiChu { get; set; }
        public int idQuan { get; set; }
        public Nullable<System.DateTime> batDauKiem { get; set; }
        public Nullable<System.DateTime> ketThucKiem { get; set; }
    }
}
