//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlCaPhe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class congThucPhaChe
    {
        public congThucPhaChe()
        {
            this.ctCongThucs = new HashSet<ctCongThuc>();
        }
    
        public int maCongThuc { get; set; }
        public string tenCongThuc { get; set; }
        public int maSanPham { get; set; }
        public string dienGiai { get; set; }
        public string nguoiTao { get; set; }
        public string nguoiDuyet { get; set; }
        public Nullable<bool> trangThai { get; set; }
        public System.DateTime ngayTao { get; set; }
        public string ghiChu { get; set; }
    
        public virtual sanPham sanPham { get; set; }
        public virtual taiKhoan taiKhoan { get; set; }
        public virtual taiKhoan taiKhoan1 { get; set; }
        public virtual ICollection<ctCongThuc> ctCongThucs { get; set; }
    }
}
