//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlCaPhe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctDatBan
    {
        public int maDatBan { get; set; }
        public int maBan { get; set; }
        public string ghiChu { get; set; }
    
        public virtual BanChoNgoi BanChoNgoi { get; set; }
        public virtual datBanOnline datBanOnline { get; set; }
    }
}
