//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlCaPhe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctDanhGia
    {
        public int maDanhGia { get; set; }
        public int maMucTieu { get; set; }
        public Nullable<int> diemSo { get; set; }
        public string dienGiai { get; set; }
    
        public virtual danhGiaNhanVien danhGiaNhanVien { get; set; }
        public virtual mucTieuDanhGia mucTieuDanhGia { get; set; }
    }
}
