//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlCaPhe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctHoaDonOrder
    {
        public int maHoaDon { get; set; }
        public int maSanPham { get; set; }
        public long donGia { get; set; }
        public Nullable<int> soLuong { get; set; }
    
        public virtual hoaDonOrder hoaDonOrder { get; set; }
        public virtual sanPham sanPham { get; set; }
    }
}
