//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlCaPhe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctHoaDonTam
    {
        public int maCtTam { get; set; }
        public int maBan { get; set; }
        public int maSP { get; set; }
        public long donGia { get; set; }
        public int soLuong { get; set; }
        public int trangThaiPhaChe { get; set; }
    
        public virtual hoaDonTam hoaDonTam { get; set; }
        public virtual sanPham sanPham { get; set; }
    }

    public class svCtHoaDonTam
    {
        public int maCtTam { get; set; }
        public int maBan { get; set; }
        public int maSP { get; set; }
        public long donGia { get; set; }
        public int soLuong { get; set; }
        public int trangThaiPhaChe { get; set; }

        public string tenSP { get; set; }
        public byte[] hinhAnh { get; set; }
    }
}
