//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlCaPhe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctTonKho
    {
        public int maSoKy { get; set; }
        public int maNguyenLieu { get; set; }
        public long donGia { get; set; }
        public Nullable<double> soLuongDauKy { get; set; }
        public Nullable<double> soLuongCuoiKyLyThuyet { get; set; }
        public Nullable<double> soLuongThucTe { get; set; }
        public Nullable<double> tyLeHaoHut { get; set; }
        public string nguyenNhanHaoHut { get; set; }
    
        public virtual nguyenLieu nguyenLieu { get; set; }
        public virtual TonKho TonKho { get; set; }
    }
}
