//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlCaPhe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class danhGiaNhanVien
    {
        public danhGiaNhanVien()
        {
            this.ctDanhGias = new HashSet<ctDanhGia>();
        }
    
        public int maDanhGia { get; set; }
        public int maTV { get; set; }
        public Nullable<System.DateTime> ngayDanhGia { get; set; }
        public string taiKhoanDanhGia { get; set; }
        public string ghiChu { get; set; }
    
        public virtual ICollection<ctDanhGia> ctDanhGias { get; set; }
        public virtual taiKhoan taiKhoan { get; set; }
        public virtual thanhVien thanhVien { get; set; }
    }
}
