//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlCaPhe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class datBanOnline
    {
        public datBanOnline()
        {
            this.ctDatBans = new HashSet<ctDatBan>();
        }
    
        public int maDatBan { get; set; }
        public string hoTenKH { get; set; }
        public string SDT { get; set; }
        public int soLuongKhach { get; set; }
        public Nullable<System.DateTime> ngayDat { get; set; }
        public Nullable<System.DateTime> ngayDenDuKien { get; set; }
        public Nullable<int> trangThai { get; set; }
        public string yeuCauThem { get; set; }
    
        public virtual ICollection<ctDatBan> ctDatBans { get; set; }
    }
}
