//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlCaPhe.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Feedback
    {
        public int maFB { get; set; }

        [Required(ErrorMessage = "*Vui lòng nhập họ và tên")]
        public string tenNguoiGui { get; set; }

        [Required(ErrorMessage = "*Vui lòng nhập email")]
        public string email { get; set; }

        [Required(ErrorMessage = "*Vui lòng nhập tiêu đề")]
        public string tieuDe { get; set; }

        [Required(ErrorMessage = "*Vui lòng nhập nội dung chi tiết")]
        public string noiDung { get; set; }
        public Nullable<System.DateTime> ngayDang { get; set; }
        public Nullable<int> trangThai { get; set; }
    }
}