//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlCaPhe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int maFB { get; set; }
        public string tenNguoiGui { get; set; }
        public string tieuDe { get; set; }
        public string noiDung { get; set; }
        public Nullable<System.DateTime> ngayDang { get; set; }
        public Nullable<int> trangThai { get; set; }
    }
}
