//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlCaPhe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoaDonTam
    {
        public hoaDonTam()
        {
            this.ctHoaDonTams = new HashSet<ctHoaDonTam>();
        }
    
        public int maBan { get; set; }
        public Nullable<int> trangThaiHoadon { get; set; }
        public Nullable<int> trangthaiphucVu { get; set; }
        public Nullable<System.DateTime> ngayLap { get; set; }
        public Nullable<System.DateTime> thoiDiemDen { get; set; }
        public string nguoiPhucVu { get; set; }
        public Nullable<long> tongTien { get; set; }
        public string ghiChu { get; set; }
    
        public virtual BanChoNgoi BanChoNgoi { get; set; }
        public virtual ICollection<ctHoaDonTam> ctHoaDonTams { get; set; }
        public virtual taiKhoan taiKhoan { get; set; }
    }
}
