//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlCaPhe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoaDonTam
    {
        public hoaDonTam()
        {
            this.ctHoaDonTams = new HashSet<ctHoaDonTam>();
        }
    
        public int maBan { get; set; }
        public Nullable<int> trangThaiHoadon { get; set; }
        public Nullable<int> trangthaiphucVu { get; set; }
        public Nullable<System.DateTime> ngayLap { get; set; }
        public Nullable<System.DateTime> thoiDiemDen { get; set; }
        public string nguoiPhucVu { get; set; }
        public Nullable<long> tongTien { get; set; }
        public string ghiChu { get; set; }
    
        public virtual BanChoNgoi BanChoNgoi { get; set; }
        public virtual ICollection<ctHoaDonTam> ctHoaDonTams { get; set; }
        public virtual taiKhoan taiKhoan { get; set; }
    }
    /// <summary>
    /// Class phục vụ cho webservice
    /// </summary>
    public class svHoaDonTam
    {
        public int maBan { get; set; }
        public int trangThaiHoadon { get; set; }
        public int trangthaiphucVu { get; set; }
        public DateTime ngayLap { get; set; }
        public DateTime thoiDiemDen { get; set; }
        public string nguoiPhucVu { get; set; }
        public long tongTien { get; set; }
        public string ghiChu { get; set; }
        public string tenBan { get; set; }
        public byte[] hinhAnhBan { get; set; }
        public int soLuongSanPham { get; set; }
        public string dienGiaiChiTiet { get; set; } //-----Thuộc tính chứa một số sản phẩm có trong hóa đơn để hiện lên listview

    }

}
