//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlCaPhe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoaDonOrder
    {
        public hoaDonOrder()
        {
            this.ctHoaDonOrders = new HashSet<ctHoaDonOrder>();
        }
    
        public int maHoaDon { get; set; }
        public int maBan { get; set; }
        public int trangThai { get; set; }
        public Nullable<System.DateTime> ngayLap { get; set; }
        public Nullable<System.DateTime> thoiDiemDen { get; set; }
        public Nullable<System.DateTime> thoiDiemDi { get; set; }
        public string nguoiPhucVu { get; set; }
        public string nguoiXuatHD { get; set; }
        public Nullable<long> chietKhau { get; set; }
        public Nullable<long> tongTien { get; set; }
        public string ghiChu { get; set; }
        public Nullable<long> tamTinh { get; set; }
    
        public virtual BanChoNgoi BanChoNgoi { get; set; }
        public virtual ICollection<ctHoaDonOrder> ctHoaDonOrders { get; set; }
        public virtual taiKhoan taiKhoan { get; set; }
        public virtual taiKhoan taiKhoan1 { get; set; }
    }
}
