//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlCaPhe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class khoHang
    {
        public khoHang()
        {
            this.phieuNhapKhoes = new HashSet<phieuNhapKho>();
            this.phieuXuatKhoes = new HashSet<phieuXuatKho>();
        }
    
        public int maKhoHang { get; set; }
        public string tenKhoHang { get; set; }
        public Nullable<int> dienTich { get; set; }
        public string sdt { get; set; }
        public string diaChi { get; set; }
        public string kinhDo { get; set; }
        public string viDo { get; set; }
        public bool trangThai { get; set; }
        public string ghiChu { get; set; }
    
        public virtual ICollection<phieuNhapKho> phieuNhapKhoes { get; set; }
        public virtual ICollection<phieuXuatKho> phieuXuatKhoes { get; set; }
    }
}
