//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlCaPhe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lichSuGia
    {
        public int maLichSu { get; set; }
        public int maSanPham { get; set; }
        public long donGia { get; set; }
        public long donGiaGoc { get; set; }
        public System.DateTime ngayCapNhat { get; set; }
        public string nguoiTao { get; set; }
        public string ghiChu { get; set; }
    
        public virtual sanPham sanPham { get; set; }
        public virtual taiKhoan taiKhoan { get; set; }
    }
}
