//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlCaPhe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class loaiNguyenLieu
    {
        public loaiNguyenLieu()
        {
            this.nguyenLieux = new HashSet<nguyenLieu>();
        }
    
        public int maLoai { get; set; }
        public string tenLoai { get; set; }
        public string dienGiai { get; set; }
        public string ghiChu { get; set; }
    
        public virtual ICollection<nguyenLieu> nguyenLieux { get; set; }
    }
}
