//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlCaPhe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nguyenLieu
    {
        public nguyenLieu()
        {
            this.ctCongThucs = new HashSet<ctCongThuc>();
            this.ctCungCaps = new HashSet<ctCungCap>();
            this.ctPhieuNhapKhoes = new HashSet<ctPhieuNhapKho>();
            this.ctPhieuXuatKhoes = new HashSet<ctPhieuXuatKho>();
            this.ctTonKhoes = new HashSet<ctTonKho>();
        }
    
        public int maNguyenLieu { get; set; }
        public string tenNguyenLieu { get; set; }
        public string moTa { get; set; }
        public int maLoai { get; set; }
        public double thoiHanSuDung { get; set; }
        public Nullable<int> tongSoLuong { get; set; }
        public string donViPhaChe { get; set; }
        public byte[] hinhAnh { get; set; }
        public bool trangThai { get; set; }
        public string ghiChu { get; set; }
        public string donViHienThi { get; set; }
        public Nullable<double> tyLeChuyenDoi { get; set; }
    
        public virtual ICollection<ctCongThuc> ctCongThucs { get; set; }
        public virtual ICollection<ctCungCap> ctCungCaps { get; set; }
        public virtual ICollection<ctPhieuNhapKho> ctPhieuNhapKhoes { get; set; }
        public virtual ICollection<ctPhieuXuatKho> ctPhieuXuatKhoes { get; set; }
        public virtual ICollection<ctTonKho> ctTonKhoes { get; set; }
        public virtual loaiNguyenLieu loaiNguyenLieu { get; set; }
    }
}
