//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlCaPhe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhaCungCap
    {
        public nhaCungCap()
        {
            this.ctCungCaps = new HashSet<ctCungCap>();
            this.ctPhieuNhapKhoes = new HashSet<ctPhieuNhapKho>();
        }
    
        public int maNhaCC { get; set; }
        public string tenNhaCC { get; set; }
        public string maSoThue { get; set; }
        public Nullable<System.DateTime> ngayThanhLap { get; set; }
        public string SDT { get; set; }
        public string FAX { get; set; }
        public string diaChi { get; set; }
        public string email { get; set; }
        public string website { get; set; }
        public byte[] logo { get; set; }
        public bool trangThai { get; set; }
        public string ghiChu { get; set; }
    
        public virtual ICollection<ctCungCap> ctCungCaps { get; set; }
        public virtual ICollection<ctPhieuNhapKho> ctPhieuNhapKhoes { get; set; }
    }
}
