//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlCaPhe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class phieuNhapKho
    {
        public phieuNhapKho()
        {
            this.ctPhieuNhapKhoes = new HashSet<ctPhieuNhapKho>();
        }
    
        public int maPhieu { get; set; }
        public int maKho { get; set; }
        public System.DateTime ngayNhap { get; set; }
        public long tongTien { get; set; }
        public string nguoiLapPhieu { get; set; }
        public string ghiChu { get; set; }
    
        public virtual ICollection<ctPhieuNhapKho> ctPhieuNhapKhoes { get; set; }
        public virtual khoHang khoHang { get; set; }
        public virtual taiKhoan taiKhoan { get; set; }
    }
}
