//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlCaPhe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class phieuXuatKho
    {
        public phieuXuatKho()
        {
            this.ctPhieuXuatKhoes = new HashSet<ctPhieuXuatKho>();
        }
    
        public int maPhieu { get; set; }
        public int maKho { get; set; }
        public Nullable<System.DateTime> ngayXuat { get; set; }
        public long tongTien { get; set; }
        public string nguoiLapPhieu { get; set; }
        public string ghiChu { get; set; }
    
        public virtual ICollection<ctPhieuXuatKho> ctPhieuXuatKhoes { get; set; }
        public virtual khoHang khoHang { get; set; }
        public virtual taiKhoan taiKhoan { get; set; }
    }
}
