//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlCaPhe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class slide
    {
        public int maSlide { get; set; }
        public byte[] hinhAnh { get; set; }
        public Nullable<bool> trangThai { get; set; }
        public Nullable<int> thuTu { get; set; }
        public Nullable<System.DateTime> ngayTao { get; set; }
        public string ghiChu { get; set; }
    }
}
