//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlCaPhe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class taiKhoan
    {
        public taiKhoan()
        {
            this.baiViets = new HashSet<baiViet>();
            this.BangGiaoViecs = new HashSet<BangGiaoViec>();
            this.congThucPhaChes = new HashSet<congThucPhaChe>();
            this.congThucPhaChes1 = new HashSet<congThucPhaChe>();
            this.danhGiaNhanViens = new HashSet<danhGiaNhanVien>();
            this.hoaDonOrders = new HashSet<hoaDonOrder>();
            this.hoaDonOrders1 = new HashSet<hoaDonOrder>();
            this.hoaDonTams = new HashSet<hoaDonTam>();
            this.lichSuGias = new HashSet<lichSuGia>();
            this.nhatKies = new HashSet<nhatKy>();
            this.phieuNhapKhoes = new HashSet<phieuNhapKho>();
            this.phieuXuatKhoes = new HashSet<phieuXuatKho>();
            this.thongBaos = new HashSet<thongBao>();
            this.TonKhoes = new HashSet<TonKho>();
        }
    
        public string tenDangNhap { get; set; }
        public string matKhau { get; set; }
        public int maTV { get; set; }
        public int maNhomTK { get; set; }
        public bool trangThai { get; set; }
        public string ghiChu { get; set; }
    
        public virtual ICollection<baiViet> baiViets { get; set; }
        public virtual ICollection<BangGiaoViec> BangGiaoViecs { get; set; }
        public virtual ICollection<congThucPhaChe> congThucPhaChes { get; set; }
        public virtual ICollection<congThucPhaChe> congThucPhaChes1 { get; set; }
        public virtual ICollection<danhGiaNhanVien> danhGiaNhanViens { get; set; }
        public virtual ICollection<hoaDonOrder> hoaDonOrders { get; set; }
        public virtual ICollection<hoaDonOrder> hoaDonOrders1 { get; set; }
        public virtual ICollection<hoaDonTam> hoaDonTams { get; set; }
        public virtual ICollection<lichSuGia> lichSuGias { get; set; }
        public virtual ICollection<nhatKy> nhatKies { get; set; }
        public virtual nhomTaiKhoan nhomTaiKhoan { get; set; }
        public virtual ICollection<phieuNhapKho> phieuNhapKhoes { get; set; }
        public virtual ICollection<phieuXuatKho> phieuXuatKhoes { get; set; }
        public virtual thanhVien thanhVien { get; set; }
        public virtual ICollection<thongBao> thongBaos { get; set; }
        public virtual ICollection<TonKho> TonKhoes { get; set; }
    }
}
