//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlCaPhe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class thongBao
    {
        public int maThongBao { get; set; }
        public string ndThongBao { get; set; }
        public string taiKhoan { get; set; }
        public Nullable<System.DateTime> ngayTao { get; set; }
        public Nullable<bool> daXem { get; set; }
        public string ghiChu { get; set; }
    
        public virtual taiKhoan taiKhoan1 { get; set; }
    }
}
