//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlCaPhe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TonKho
    {
        public TonKho()
        {
            this.ctTonKhoes = new HashSet<ctTonKho>();
        }
    
        public int maSoKy { get; set; }
        public System.DateTime ngayKiem { get; set; }
        public Nullable<long> tongTien { get; set; }
        public string nguoiKiem { get; set; }
        public string ghiChu { get; set; }
    
        public virtual ICollection<ctTonKho> ctTonKhoes { get; set; }
        public virtual taiKhoan taiKhoan { get; set; }
    }
}
